name: offerswala
description: "OffersWala App Made by Ram Gupta"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  page_view_dot_indicator: ^2.3.0
  url_launcher: ^6.2.5
  geolocator:
  geocoding:
  geocode: ^1.0.3
  simple_form_validations: ^1.0.1
  flutter_image_slideshow: ^0.1.6
  searchfield: ^1.0.1
  page_transition: ^2.1.0
  get: ^4.6.6
  floating_navigation_bar: ^0.0.5
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/signup/
    - assets/images/icons/
    - assets/images/icons/categories/
    - assets/images/image_slider/
    - assets/images/icons/brands/
    - assets/images/grid/
    - assets/images/ticker/
    - assets/images/offerlist_card/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
          style: normal
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
